import 'package:sushi_food_app/modules/home/models/sushi.dart';

Map<String, List<Sushi>> sushis = {
  'nigiri': [
    Sushi(
      id: 1,
      image: 'assets/images/nigiri/nigiri-1.png',
      price: 4.10,
      name: 'Maguro nigiri',
      ingredient: 'Tuna',
      isFavorite: false,
    ),
    Sushi(
      id: 2,
      image: 'assets/images/nigiri/nigiri-2.png',
      price: 4.30,
      name: 'Sake nigiri',
      ingredient: 'Norwegian salmon',
      isFavorite: false,
    ),
    Sushi(
      id: 3,
      image: 'assets/images/nigiri/nigiri-3.png',
      price: 4.50,
      name: 'Amaebi nigiri',
      ingredient: 'Sweet shrimp',
      isFavorite: false,
    ),
    Sushi(
      id: 4,
      image: 'assets/images/nigiri/nigiri-4.png',
      price: 4.70,
      name: 'Unagi nigiri',
      ingredient: 'Smoked eel',
      isFavorite: false,
    ),
    Sushi(
      id: 5,
      image: 'assets/images/nigiri/nigiri-5.png',
      price: 4.90,
      name: 'Nigiri Sushi',
      ingredient: 'Rice & fish',
      isFavorite: false,
    ),
    Sushi(
      id: 6,
      image: 'assets/images/nigiri/nigiri-6.png',
      price: 4.60,
      name: 'Dashi',
      ingredient: 'Dashi',
      isFavorite: false,
    ),
  ],
  'roll': [
    Sushi(
      id: 7,
      image: 'assets/images/rolls/roll-1.png',
      price: 4.90,
      name: 'Kani Maki',
      ingredient: 'Crab sticks',
      isFavorite: false,
    ),
    Sushi(
      id: 8,
      image: 'assets/images/rolls/roll-2.png',
      price: 4.70,
      name: 'Fresh Salmon',
      ingredient: 'Fillet & avocado',
      isFavorite: false,
    ),
    Sushi(
      id: 9,
      image: 'assets/images/rolls/roll-3.png',
      price: 4.10,
      name: 'Tikka Maki',
      ingredient: 'Cooked tuna',
      isFavorite: false,
    ),
    Sushi(
      id: 10,
      image: 'assets/images/rolls/roll-4.png',
      price: 4.50,
      name: 'Smoked Salmon',
      ingredient: 'Cucumber',
      isFavorite: false,
    ),
    Sushi(
      id: 11,
      image: 'assets/images/rolls/roll-5.png',
      price: 4.20,
      name: 'Smoked',
      ingredient: 'Cucumber',
      isFavorite: false,
    ),
    Sushi(
      id: 12,
      image: 'assets/images/rolls/roll-6.png',
      price: 4.40,
      name: 'Kani Make',
      ingredient: 'Crab sticks',
      isFavorite: false,
    ),
  ],
  'soup': [
    Sushi(
      id: 13,
      image: 'assets/images/soups/soup-1.png',
      price: 4.10,
      name: 'Miso',
      ingredient: 'Dashi & miso',
      isFavorite: false,
    ),
    Sushi(
      id: 14,
      image: 'assets/images/soups/soup-2.png',
      price: 4.30,
      name: 'Tonjiru',
      ingredient: 'Chicken Tonjiru',
      isFavorite: false,
    ),
    Sushi(
      id: 15,
      image: 'assets/images/soups/soup-3.png',
      price: 4.50,
      name: 'Imoni',
      ingredient: 'Beef and potatoes',
      isFavorite: false,
    ),
    Sushi(
      id: 16,
      image: 'assets/images/soups/soup-4.png',
      price: 4.70,
      name: 'Ramen',
      ingredient: 'Tonkotsu ramen',
      isFavorite: false,
    ),
    Sushi(
      id: 17,
      image: 'assets/images/soups/soup-5.png',
      price: 4.90,
      name: 'Suimono',
      ingredient: 'Ushiojiru',
      isFavorite: false,
    ),
    Sushi(
      id: 18,
      image: 'assets/images/soups/soup-6.png',
      price: 4.60,
      name: 'Dashi',
      ingredient: 'Dashi',
      isFavorite: false,
    )
  ]
};
